version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - pip install awscli==1.16.141
      - yum install jq
      - BUILDROOT=$(pwd)
      - echo "CodeBuild Id $CODEBUILD_BUILD_ID"
      - npm install -g db-migrate db-migrate-pg

  build:
    commands:
      - export DB_NAME="<DBNAME>"
      - export DB_PORT="5432"
      - temprole=$(aws sts assume-role --role-arn "arn:aws:iam::$AWS_ACCOUNT:role/ToolsAcctCodePipelineCloudFormationRole" --role-session-name "Database-Deploy-$AWS_ACCOUNT")
      - echo $temprole
      - export AWS_ACCESS_KEY_ID=$(echo $temprole | jq .Credentials.AccessKeyId | xargs)
      - export AWS_SECRET_ACCESS_KEY=$(echo $temprole | jq .Credentials.SecretAccessKey | xargs)
      - export AWS_SESSION_TOKEN=$(echo $temprole | jq .Credentials.SessionToken | xargs)
      - aws sts get-caller-identity
      - dbinfo=$(aws secretsmanager get-secret-value --secret-id quasardeploy-postgres --version-stage AWSCURRENT  --query SecretString)
      - dbinfo=$(echo $dbinfo | sed -e 's/\\//g' | sed -e 's/"{/{/g' | sed -e 's/}"/}/g')
      - export DB_PASSWORD=$(echo $dbinfo | jq .password | xargs)
      - export DB_USERID=$(echo $dbinfo | jq .username | xargs)
      - unset AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN
      - aws sts get-caller-identity
      - aws --debug s3 cp "s3://quasar-bastion-keys/bastion-$BUILD_ENV.pem" .
      - chmod 400 "bastion-$BUILD_ENV.pem"
      - ssh -v -4 -f -i "bastion-$BUILD_ENV.pem" -L "5432:$BUILD_ENV-dbcluster.nelnet.io:3306" "ec2-user@$BUILD_ENV-bastion.nelnet.io" -N -M -S "~/deploysession" -o "StrictHostKeyChecking no" -g
      - export NODE_ENV="create"
      - |
        set +e
        db-migrate db:create "$DB_NAME"
        set -e
      - |
      - export NODE_ENV="migrate"
      - db-migrate check
      - db-migrate up
    finally:
      - |
        set +e
        ssh -S "~/deploysession" -O exit "ec2-user@$BUILD_ENV-bastion.nelnet.io"
        export DB_PASSWORD=""
        export DB_USERID=""
        rm "bastion-$BUILD_ENV.pem" -f
        cat /dev/null > ~/.bash_history
        set -e
      - |

